# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d46ade08de274d1ad91c98345511fdcacc4007050d4b0a657d9c933a5638f9c4d020968b4d8b75bad38bd174539f27b3412de007aa8020267af75c84db020e7

test:
  secret_key_base: 3ba3871f4fc6599a0995fd6ee18bd23750a9c1dbe0a1458eacfb6a6b6a108a704e45162993561469bd77c6fdd88d23705bfff7efec6927c54fed54b293d42b10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
